//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Pose p_default_killhouse_Pose;
        
        private static SteamVR_Action_Skeleton p_default_killhouse_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_default_killhouse_SkeletonRightHand;
        
        private static SteamVR_Action_Boolean p_default_killhouse_Trigger_Button;
        
        private static SteamVR_Action_Boolean p_default_killhouse_Trigger_Touch;
        
        private static SteamVR_Action_Boolean p_default_killhouse_Primary2Axis_Button;
        
        private static SteamVR_Action_Boolean p_default_killhouse_Primary2Axis_Touch;
        
        private static SteamVR_Action_Boolean p_default_killhouse_Secondary2Axis_Button;
        
        private static SteamVR_Action_Boolean p_default_killhouse_Secondary2Axis_Touch;
        
        private static SteamVR_Action_Boolean p_default_killhouse_A_Button;
        
        private static SteamVR_Action_Boolean p_default_killhouse_A_Button_Touch;
        
        private static SteamVR_Action_Boolean p_default_killhouse_B_Button;
        
        private static SteamVR_Action_Boolean p_default_killhouse_B_Button_Touch;
        
        private static SteamVR_Action_Boolean p_default_killhouse_Grip_Button;
        
        private static SteamVR_Action_Boolean p_default_killhouse_Grip_Touch;
        
        private static SteamVR_Action_Single p_default_killhouse_Trigger_Axis;
        
        private static SteamVR_Action_Single p_default_killhouse_Grip_Squeeze;
        
        private static SteamVR_Action_Single p_default_killhouse_Thumb_Squeeze;
        
        private static SteamVR_Action_Vector2 p_default_killhouse_Primary2Axis_Axes;
        
        private static SteamVR_Action_Vector2 p_default_killhouse_Secondary2Axis_Axes;
        
        private static SteamVR_Action_Vibration p_default_killhouse_Haptic;
        
        public static SteamVR_Action_Pose default_killhouse_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_killhouse_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_killhouse_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Boolean default_killhouse_Trigger_Button
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_Trigger_Button.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_killhouse_Trigger_Touch
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_Trigger_Touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_killhouse_Primary2Axis_Button
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_Primary2Axis_Button.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_killhouse_Primary2Axis_Touch
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_Primary2Axis_Touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_killhouse_Secondary2Axis_Button
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_Secondary2Axis_Button.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_killhouse_Secondary2Axis_Touch
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_Secondary2Axis_Touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_killhouse_A_Button
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_A_Button.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_killhouse_A_Button_Touch
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_A_Button_Touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_killhouse_B_Button
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_B_Button.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_killhouse_B_Button_Touch
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_B_Button_Touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_killhouse_Grip_Button
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_Grip_Button.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_killhouse_Grip_Touch
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_Grip_Touch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Single default_killhouse_Trigger_Axis
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_Trigger_Axis.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single default_killhouse_Grip_Squeeze
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_Grip_Squeeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single default_killhouse_Thumb_Squeeze
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_Thumb_Squeeze.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_killhouse_Primary2Axis_Axes
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_Primary2Axis_Axes.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_killhouse_Secondary2Axis_Axes
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_Secondary2Axis_Axes.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vibration default_killhouse_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_killhouse_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_killhouse_Pose,
                    SteamVR_Actions.default_killhouse_SkeletonLeftHand,
                    SteamVR_Actions.default_killhouse_SkeletonRightHand,
                    SteamVR_Actions.default_killhouse_Trigger_Button,
                    SteamVR_Actions.default_killhouse_Trigger_Touch,
                    SteamVR_Actions.default_killhouse_Primary2Axis_Button,
                    SteamVR_Actions.default_killhouse_Primary2Axis_Touch,
                    SteamVR_Actions.default_killhouse_Secondary2Axis_Button,
                    SteamVR_Actions.default_killhouse_Secondary2Axis_Touch,
                    SteamVR_Actions.default_killhouse_A_Button,
                    SteamVR_Actions.default_killhouse_A_Button_Touch,
                    SteamVR_Actions.default_killhouse_B_Button,
                    SteamVR_Actions.default_killhouse_B_Button_Touch,
                    SteamVR_Actions.default_killhouse_Grip_Button,
                    SteamVR_Actions.default_killhouse_Grip_Touch,
                    SteamVR_Actions.default_killhouse_Trigger_Axis,
                    SteamVR_Actions.default_killhouse_Grip_Squeeze,
                    SteamVR_Actions.default_killhouse_Thumb_Squeeze,
                    SteamVR_Actions.default_killhouse_Primary2Axis_Axes,
                    SteamVR_Actions.default_killhouse_Secondary2Axis_Axes,
                    SteamVR_Actions.default_killhouse_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_killhouse_Pose,
                    SteamVR_Actions.default_killhouse_SkeletonLeftHand,
                    SteamVR_Actions.default_killhouse_SkeletonRightHand,
                    SteamVR_Actions.default_killhouse_Trigger_Button,
                    SteamVR_Actions.default_killhouse_Trigger_Touch,
                    SteamVR_Actions.default_killhouse_Primary2Axis_Button,
                    SteamVR_Actions.default_killhouse_Primary2Axis_Touch,
                    SteamVR_Actions.default_killhouse_Secondary2Axis_Button,
                    SteamVR_Actions.default_killhouse_Secondary2Axis_Touch,
                    SteamVR_Actions.default_killhouse_A_Button,
                    SteamVR_Actions.default_killhouse_A_Button_Touch,
                    SteamVR_Actions.default_killhouse_B_Button,
                    SteamVR_Actions.default_killhouse_B_Button_Touch,
                    SteamVR_Actions.default_killhouse_Grip_Button,
                    SteamVR_Actions.default_killhouse_Grip_Touch,
                    SteamVR_Actions.default_killhouse_Trigger_Axis,
                    SteamVR_Actions.default_killhouse_Grip_Squeeze,
                    SteamVR_Actions.default_killhouse_Thumb_Squeeze,
                    SteamVR_Actions.default_killhouse_Primary2Axis_Axes,
                    SteamVR_Actions.default_killhouse_Secondary2Axis_Axes};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_killhouse_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_killhouse_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_killhouse_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_killhouse_Trigger_Button,
                    SteamVR_Actions.default_killhouse_Trigger_Touch,
                    SteamVR_Actions.default_killhouse_Primary2Axis_Button,
                    SteamVR_Actions.default_killhouse_Primary2Axis_Touch,
                    SteamVR_Actions.default_killhouse_Secondary2Axis_Button,
                    SteamVR_Actions.default_killhouse_Secondary2Axis_Touch,
                    SteamVR_Actions.default_killhouse_A_Button,
                    SteamVR_Actions.default_killhouse_A_Button_Touch,
                    SteamVR_Actions.default_killhouse_B_Button,
                    SteamVR_Actions.default_killhouse_B_Button_Touch,
                    SteamVR_Actions.default_killhouse_Grip_Button,
                    SteamVR_Actions.default_killhouse_Grip_Touch};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.default_killhouse_Trigger_Axis,
                    SteamVR_Actions.default_killhouse_Grip_Squeeze,
                    SteamVR_Actions.default_killhouse_Thumb_Squeeze};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.default_killhouse_Primary2Axis_Axes,
                    SteamVR_Actions.default_killhouse_Secondary2Axis_Axes};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.default_killhouse_SkeletonLeftHand,
                    SteamVR_Actions.default_killhouse_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_killhouse_Trigger_Button,
                    SteamVR_Actions.default_killhouse_Trigger_Touch,
                    SteamVR_Actions.default_killhouse_Primary2Axis_Button,
                    SteamVR_Actions.default_killhouse_Primary2Axis_Touch,
                    SteamVR_Actions.default_killhouse_Secondary2Axis_Button,
                    SteamVR_Actions.default_killhouse_Secondary2Axis_Touch,
                    SteamVR_Actions.default_killhouse_A_Button,
                    SteamVR_Actions.default_killhouse_A_Button_Touch,
                    SteamVR_Actions.default_killhouse_B_Button,
                    SteamVR_Actions.default_killhouse_B_Button_Touch,
                    SteamVR_Actions.default_killhouse_Grip_Button,
                    SteamVR_Actions.default_killhouse_Grip_Touch,
                    SteamVR_Actions.default_killhouse_Trigger_Axis,
                    SteamVR_Actions.default_killhouse_Grip_Squeeze,
                    SteamVR_Actions.default_killhouse_Thumb_Squeeze,
                    SteamVR_Actions.default_killhouse_Primary2Axis_Axes,
                    SteamVR_Actions.default_killhouse_Secondary2Axis_Axes};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_killhouse_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default_killhouse/in/Pose")));
            SteamVR_Actions.p_default_killhouse_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default_killhouse/in/SkeletonLeftHand")));
            SteamVR_Actions.p_default_killhouse_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default_killhouse/in/SkeletonRightHand")));
            SteamVR_Actions.p_default_killhouse_Trigger_Button = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default_killhouse/in/Trigger_Button")));
            SteamVR_Actions.p_default_killhouse_Trigger_Touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default_killhouse/in/Trigger_Touch")));
            SteamVR_Actions.p_default_killhouse_Primary2Axis_Button = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default_killhouse/in/Primary2Axis_Button")));
            SteamVR_Actions.p_default_killhouse_Primary2Axis_Touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default_killhouse/in/Primary2Axis_Touch")));
            SteamVR_Actions.p_default_killhouse_Secondary2Axis_Button = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default_killhouse/in/Secondary2Axis_Button")));
            SteamVR_Actions.p_default_killhouse_Secondary2Axis_Touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default_killhouse/in/Secondary2Axis_Touch")));
            SteamVR_Actions.p_default_killhouse_A_Button = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default_killhouse/in/A_Button")));
            SteamVR_Actions.p_default_killhouse_A_Button_Touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default_killhouse/in/A_Button_Touch")));
            SteamVR_Actions.p_default_killhouse_B_Button = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default_killhouse/in/B_Button")));
            SteamVR_Actions.p_default_killhouse_B_Button_Touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default_killhouse/in/B_Button_Touch")));
            SteamVR_Actions.p_default_killhouse_Grip_Button = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default_killhouse/in/Grip_Button")));
            SteamVR_Actions.p_default_killhouse_Grip_Touch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default_killhouse/in/Grip_Touch")));
            SteamVR_Actions.p_default_killhouse_Trigger_Axis = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default_killhouse/in/Trigger_Axis")));
            SteamVR_Actions.p_default_killhouse_Grip_Squeeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default_killhouse/in/Grip_Squeeze")));
            SteamVR_Actions.p_default_killhouse_Thumb_Squeeze = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default_killhouse/in/Thumb_Squeeze")));
            SteamVR_Actions.p_default_killhouse_Primary2Axis_Axes = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default_killhouse/in/Primary2Axis_Axes")));
            SteamVR_Actions.p_default_killhouse_Secondary2Axis_Axes = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default_killhouse/in/Secondary2Axis_Axes")));
            SteamVR_Actions.p_default_killhouse_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/default_killhouse/out/Haptic")));
        }
    }
}
