//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default_killhouse : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_killhouse_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_killhouse_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_killhouse_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean Trigger_Button
        {
            get
            {
                return SteamVR_Actions.default_killhouse_Trigger_Button;
            }
        }
        
        public virtual SteamVR_Action_Boolean Trigger_Touch
        {
            get
            {
                return SteamVR_Actions.default_killhouse_Trigger_Touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Primary2Axis_Button
        {
            get
            {
                return SteamVR_Actions.default_killhouse_Primary2Axis_Button;
            }
        }
        
        public virtual SteamVR_Action_Boolean Primary2Axis_Touch
        {
            get
            {
                return SteamVR_Actions.default_killhouse_Primary2Axis_Touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Secondary2Axis_Button
        {
            get
            {
                return SteamVR_Actions.default_killhouse_Secondary2Axis_Button;
            }
        }
        
        public virtual SteamVR_Action_Boolean Secondary2Axis_Touch
        {
            get
            {
                return SteamVR_Actions.default_killhouse_Secondary2Axis_Touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean A_Button
        {
            get
            {
                return SteamVR_Actions.default_killhouse_A_Button;
            }
        }
        
        public virtual SteamVR_Action_Boolean A_Button_Touch
        {
            get
            {
                return SteamVR_Actions.default_killhouse_A_Button_Touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean B_Button
        {
            get
            {
                return SteamVR_Actions.default_killhouse_B_Button;
            }
        }
        
        public virtual SteamVR_Action_Boolean B_Button_Touch
        {
            get
            {
                return SteamVR_Actions.default_killhouse_B_Button_Touch;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip_Button
        {
            get
            {
                return SteamVR_Actions.default_killhouse_Grip_Button;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip_Touch
        {
            get
            {
                return SteamVR_Actions.default_killhouse_Grip_Touch;
            }
        }
        
        public virtual SteamVR_Action_Single Trigger_Axis
        {
            get
            {
                return SteamVR_Actions.default_killhouse_Trigger_Axis;
            }
        }
        
        public virtual SteamVR_Action_Single Grip_Squeeze
        {
            get
            {
                return SteamVR_Actions.default_killhouse_Grip_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Single Thumb_Squeeze
        {
            get
            {
                return SteamVR_Actions.default_killhouse_Thumb_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Primary2Axis_Axes
        {
            get
            {
                return SteamVR_Actions.default_killhouse_Primary2Axis_Axes;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Secondary2Axis_Axes
        {
            get
            {
                return SteamVR_Actions.default_killhouse_Secondary2Axis_Axes;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_killhouse_Haptic;
            }
        }
    }
}
